### ISSUE TITLE
publish: getsentry/sentry-dotnet@4.1.0

### ISSUE THREAD

**Issue by getsentry-release** [getsentry/publish#3389]
Requested by: @jamescrosswell

Merge target: (default)

Quick links:
- [View changes](https://github.com/getsentry/sentry-dotnet/compare/bfb0446821d527ee45c4d9d8e55bf259528c5404...refs/heads/release/4.1.0)
- [View check runs](https://github.com/getsentry/sentry-dotnet/commit/b7644eb991f6e98efaf2db671c341e71d6963cf0/checks/)

Assign the **accepted** label to this issue to approve the release.
Leave the `#retract` comment under this issue to retract the release (original issuer only).

### Targets

 - [ ] nuget
 - [ ] github
 - [ ] registry

Targets marked with a checkbox have already been executed.  Administrators can manually tick a checkbox to force craft to skip it.

**Comment by bruno-garcia** [comment]
```
  STDOUT: dotnet: Pushing Sentry.4.1.0.nupkg to 'https://www.nuget.org/api/v2/package'...
  dotnet:   PUT https://www.nuget.org/api/v2/package/
  dotnet:   BadRequest https://www.nuget.org/api/v2/package/ 1167ms
  dotnet: error: Response status code does not indicate success: 400 (A local file header is corrupt.).
  dotnet:
  dotnet:
  dotnet: Usage: dotnet nuget push [arguments] [options]
  dotnet:
  dotnet: Arguments:
  dotnet:   [root]  Specify the path to the package and your API key to push the package to the server.
  dotnet:
  dotnet: Options:
  dotnet:   -h|--help                      Show help information
  dotnet:   --force-english-output         Forces the application to run using an invariant, English-based culture.
  dotnet:   -s|--source <source>           Package source (URL, UNC/folder path or package source name) to use. Defaults to DefaultPushSource if specified in NuGet.Config.
  dotnet:   -ss|--symbol-source <source>   Symbol server URL to use.
  dotnet:   -t|--timeout <timeout>         Timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes).
  dotnet:   -k|--api-key <apiKey>          The API key for the server.
  dotnet:   -sk|--symbol-api-key <apiKey>  The API key for the symbol server.
  dotnet:   -d|--disable-buffering         Disable buffering when pushing to an HTTP(S) server to decrease memory usage.
  dotnet:   -n|--no-symbols                If a symbols package exists, it will not be pushed to a symbols server.
  dotnet:   --no-service-endpoint          Does not append "api/v2/package" to the source URL.
  dotnet:   --interactive                  Allow the command to block and require manual action for operations like authentication.
  dotnet:   --skip-duplicate               If a package and version already exists, skip it and continue with the next package in the push, if any.
  dotnet:
  dotnet:
```
